version: '3.8'

services:
  db_esme:
    image: postgres:13
    container_name: db_esme
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mot_de_passe
      POSTGRES_DB: esme_inge
    ports:
      - "5432:5432"

  flask_app:
    build: .
    container_name: db_flask_app_esme
    depends_on:
      - db_esme
    environment:
      - DATABASE_URL=postgresql://myuser:mot_de_passe@db_esme:5432/esme_inge
    ports:
 HEAD
      - "5005:5000"

      - "5009:5000"
 c16a1e04af6932616915af69af6a4105ed541932
